### ISSUE TITLE
pending corrections for the "BPF and tcpdump" article

### ISSUE THREAD

**Issue by infrastation** [andreaskaris/blog#2]
Hello Andreas.

Thank you for publishing this article. I wonder if you had a chance to review a couple technical corrections I sent you by e-mail on 2022-06-29. The matter is, your article would be a welcome addition to the documentation section of www.tcpdump.org, but it would be right not to leave known issues uncorrected. Let me know in case you need any additional information.

**Comment by infrastation** [comment]
I take it as a "no".

**Comment by andreaskaris** [comment]
Hi! I'll work on the corrections, sorry, I completely missed this one here!

**Comment by andreaskaris** [comment]
I wrote the blog post ages ago so I have to reread it and reunderstand it. I'll make the changes hopefully this weekend

Below the info that you had sent me

-----

Thank you for publishing this article, it was interesting to follow the
line of thought.  There is one thing though that is incorrect: when it
discusses the handling of "tcpdump -d", it refers to the following code
fragment:

                case 'D':
                        Dflag++;
                        break;

This is not related, as you might notice from the #ifdef around this
case block.  The correct code is this:

                case 'd':
                        ++dflag;
                        break;


Also near the end, when the text compares nbpf_compile and tcpdump for
"iptables -m bpf" purposes, it says:

"Compare this to the tcpdump output which will not work:"

Note that in this example nbpf_compile uses DLT_RAW (explicitly) and
tcpdump uses DLT_EN10MB (implicitly), so the difference in bytecode
outputs comes from the fact the latter DLT has an Ethernet header before
the data, so it in fact requires different BPF instructions to get to
the protocol fields of interest.  If you use DLT_RAW (as iptables
requires) in both cases, the only difference will be in the last return
value (which is the snapshot length):

tcpdump -y RAW -d tcp port 8080 -ddd | tr '\n' ','

I hope this helps to improve the article.

**Comment by andreaskaris** [comment]
Also by the way, a big thank you for the feedback! I meant to get back to this for a long time but I just didn't have the time!

**Comment by infrastation** [comment]
You are welcome. The corrections should be only a few lines, let me know if you would prefer to receive a pull request.

**Comment by andreaskaris** [comment]
I integrated your changes, proofread, rephrased and restructured quite a bit. Let me know what you think about the new version: https://andreaskaris.github.io/blog/networking/bpf-and-tcpdump/

**Comment by infrastation** [comment]
Thank you very much, I confirm the new revision addresses both of these points (most importantly, the effect of DLT choice) and makes a number of other improvements. The link to the post is now in the documentation section of www.tcpdump.org. If you wish, you might want to address a few more minor points:
* In the "Prerequisites for tcpdump" section the text says: "In my case, DLT_RAW was not supported by my distribution's build (RHEL 8)." -- the actual issue here likely is that older tcpdump versions did not support `-y` for `-d`, so one would have to use `-d`, but instead of `-y RAW` either point tcpdump to an interface that captures using `DLT_RAW` (for example, the `ipip` variety of Linux tunnel interface) or to ask it to read an existing pcap savefile with `DLT_RAW`, neither of which is convenient (or, strictly speaking, necessary). tcpdump 4.99.0 includes a fix to resolve this unnecessary complication.
* Ibid., the first `make install` (in the libpcap directory) could be just `make` because by default tcpdump will link statically with `../libpcap/libpcap.a`.
* In "tcpdump with an explicit offset expression" the expression could use `link[22:2]`, which is an alias of `ether[22:2]`, but does not require the subsequent clarifications that Ethernet is not involved.

Please close this when you find this matter resolved.

**Comment by infrastation** [comment]
Alright, this looks fully resolved, so let's close it. Thank you for your efforts!

**Comment by andreaskaris** [comment]
Thanks for linking it! :-)
